version: '3'
services:
  sonic-server-simple:
    image: "zhouyixun/sonic-server-simple:v1.0.0"
    environment:
      - REDIS_DATABASE=0
      - REDIS_HOST=sonic-redis
      - REDIS_PORT=6379
      - RABBIT_HOST=sonic-rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=guest
      - RABBIT_VHOST=/
      - MYSQL_HOST=sonic-mysql
      - MYSQL_DATABASE=sonic
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Sonic!@#123
    networks:
      - sonic-network
    volumes:
      - files:/keepFiles/
      - files:/imageFiles/
      - files:/recordFiles/
      - files:/logs/
    ports:
      - "8094:8094"
  sonic-client-web:
    image: "zhouyixun/sonic-client-web:v1.0.3"
    networks:
      - sonic-network
    ports:
      - "3000:80"
#如果本地没有部署mysql、redis、rabbitmq，可以放开以下注释，但是数据重启后就会丢失，需要持久化的话自己挂载目录即可
#  sonic-mysql:
#    image: "mysql:5.7"
#    hostname: sonic-mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=Sonic!@#123
#    ports:
#      - "3307:3306"
#    networks:
#      - sonic-network
#  sonic-redis:
#    image: "redis:latest"
#    hostname: sonic-redis
#    ports:
#      - "6380:6379"
#    networks:
#      - sonic-network
#  sonic-rabbitmq:
#    image: "rabbitmq:3.8.16-management"
#    hostname: sonic-rabbitmq
#    ports:
#      - 15673:15672
#      - 5673:5672
#    networks:
#      - sonic-network

volumes:
  files:

networks:
  sonic-network:
    driver: bridge